name: "Test GitHub Kubevirt Runners"
on:
  workflow_dispatch:
      
jobs:
  arc-kubevirt-test:
    name: Test KuberVirt KRD Runners
    runs-on: vm-self-hosted
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # refs/tags/v4.1.7
      - name: Vagrant demo
        run: |
          export VAGRANT_DEFAULT_PROVIDER=virtualbox
          vagrant box list
          pushd "$(mktemp -d)"
          cat <<EOT >vagrant_file.erb
          Vagrant.configure("2") do |config|
            config.vm.provider :libvirt
            config.vm.provider :virtualbox

            config.vm.box = "<%= box_name %>"
          
            [:virtualbox, :libvirt].each do |provider|
            config.vm.provider provider do |p|
                p.cpus = 2
                p.memory = 1024
              end
            end
          end
          EOT
          vagrant init generic/alpine316 --box-version 3.5.0 --template vagrant_file.erb
          vagrant up || :
          vagrant halt
          vagrant package
          if [ ! -f package.box ]; then
              warn "Vagrant couldn't package the running box"
          fi
          vagrant destroy -f || :
          popd
