name: "Test GitHub Kubevirt Runners"
on:
  workflow_dispatch:
      
jobs:
  arc-kubevirt-test:
    name: Test KuberVirt KRD Runners
    runs-on: kubevirt-runner-set
    steps:
      - name: Show current state
        run: ls /tmp
      - name: Create a directory
        run: mktemp -d
      - name: Create a file
        run: touch "/tmp/$(date +"%T")"
      - name: Show current state
        run: ls /tmp
